### ISSUE TITLE
Problem with folders and LimaConf environment

### ISSUE THREAD

**Issue by FaizaGara** [aymara/lima#27] opened 2015-06-02 11:16 UTC
Bug when folder names have accents. LimaConf files are not found.
Unable to open qslog configuration file:
/home/administrateur/Téléchargements/LivraisonMai/Dist/share/config/amose/log4cpp.properties
Configure Problem

**Comment by kleag** [comment] 2016-05-11 15:10
Cannot reproduce with the current master.
Do you still have the problem ?

**Comment by kleag** [comment] 2017-03-01 11:10
No answer. Closing.

**Closed by kleag** 2017-03-01 11:10 UTC
Labels: bug, cannot reproduce
